language: java
# Only build tags
if: tag IS present
install:
- true
script:
- gradle buildAll
deploy:
  provider: releases
  api_key:
    secure: V4iWzP4pbLJDk5e6owe6ztlinLnFgH4iVKtp/XMYbDk3YRFe51zgO/vO9pUmjCPG7UdD4bVZm/MAwwuunxHJaFcXFbSSKPm3AZunU1bl8XHyD3q8AXtrdhKzS1SGgzGafrftxlwjcTYWCXeTabNWp4mXWFJX+wvhI3TAD+SihqhQe9btcftpDWJSE/wcuZroozp2m+gU7bcyC5GRoTbol8DSwXm4E+tdSONdaOo1GPaoy2USMWCSIO0nFNic3Adm/cqmo3Kmzu4gvSIFkmvGIXz6n/DN8dEQZti5crqo3KmE1bwUJ7PVCkwWq4agP0bK3AthUgKRM056X+G4DQJNHwBc4IapyhDVH3L2O3FML28fXHGbcsJNbqolP412mnr2p0Tpy/67DKP64SP6+UcZjcJt4gBmUmrjN6lBaRnO9Fpt0y0if1jA50MLjEMc6g1mwvTY1utPYgZrOw09eN++Fhd3rNoNhoAp4c5UjIfHOsct8RlVaaLHSLKfx5XAuLZ8aMaE/R3i5qyYJqM9OKgOog6EtP3RHXa7cA3BmWX/A6W7yCdZhdFSJ/AQOy41EQANgY72jrcH+38wF0hUEZQRyyZo7A5UWIko5pM0YN7AIWSRClnUAWz4zYJZufBfmLdIOB40cjtf4nu/5pqU2k3ADtLeft04KsDzL/3Tp9Lv9z4=
  file_glob: true
  file:
  - build/Galactic Science_*_Client.zip
  - build/Galactic Science_*_Server.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: mZbXFMRQLQ0Ej3FNFzdlX99+Ma68wLhCsaE2Gbz8JLeBxUzuHSCUZgA5dnqSi2/akDBQO6s1ekUxzWuM6/Plh4bUX/xeIL+SqQ3j0I2Txj5GIGQJN9Is+pe1dL858pVM0o+MzjB6d170/OkO4IjahNq935M3v20/YbXWytOmY2vvFp0GYwshrWrb/dnhUhMLdW8Ya80a2wAKFx/XvhQSGTtv/a+FKSwcNPdIqXh1RGjJKx5LsNQQF4f/+tTU6pIFyeJcRtLVN2t+4rHorVHCX76g7yI6HxQz87+mLhgtLmRvaol4rMPfGWj4LEFqB2ym7WIA9YBkN3x1JGjKJBmOofztd57GBFST2hiqp9+C6uX0TL1KN3U7mAmKkPtaptzGjBlHp6j6yzC17YfP+EowdxFsrJLoqP5KBJPkUrEQGBBeTPbi9aSaKM7tamX4nK5L0beq6uMjqUCbbthPNlFh8DBiDKpBjpukOPPgUFh8/zvhnyc2jk4xqrhfGQkMlMtCv402Dtiwdlhi7yYaaYqxhMHPvLI8CTM4vchHWcm460tksM1H5vyDza0YqlNnJ2rMGjyz+Z8OMzy18WmIeuNi9A+xPSkMLj6GtEPG3kTR4ftcNaspRruLIbt5Zkf8Q0z6MZTg3tN1lS/ORhNtS0TrU6la/RgmmOl8RwX1SXkyPBk=
