## Use java for gradle
language: java

## Keep files for deploy
skip_cleanup: true

## Skip install
install: 
  - true

## Use provided gradle
# before_install:
#  - "chmod +x gradlew"
# script: 
#   - "./gradlew buildAll"
##

# Use system gradle
script: 
  - "gradle buildAll"
##

## deploy release to github
deploy:
  provider: releases
  api_key:
    secure: X897zWbauuhY41eEvB1Tmcu/nq3mtWVDv7RSyPBhrPLdUtQ+RDrX2VaSrxCpm7DggALSbiRxoPMO5nrufBkIGge3wKAPBA+iPJ7hJYDu496fuvUFnpQomZfoIbEBydh1438ILqPPsJxNtJtmqcukVrUHz8rWzkqG9JGSE4gHcgjpPAZHwEFtgsD4oS8YKo9aWGCsgXAswzF/p//sAW3gj/rwG4XzploUbnhmfhvn4DpEegINLEM+JGd9Q7enFRDHS7JEYZZ0XCQ8XP9JQDlRyGRAJwy8NH0cIqat8TdIpEVz+p9HHx+c0Q7FPCCsFFpoLjHq/m/l48C8l6yyA5vdeIiKaXD6M1tk4XPyrjRpy5oduiiWGtXnSzkmzt5uCKIz/KP91mc54ZfDKLHRk/CP31HThI5yPooq/14NFyKAvfKFBdni+xohEYloqtXF1HVBX12yhDTktZNXSPnotsfJmuZ84GBKM5napSPYIGvhhFY/Q9kwXXOrO2nj+U8AxJxC6MLWeeZz1x4cY7ODZ3VH5Dro79oqeKDIR3YUGQ4c/YNGW/CYJ0wc0VeSGmuWJguxr3GT0upSZNITVGcDgWUWd4XXo2m5xahQgteIOs+S27wnF9Ff4fQaS2Gt7nrHTkGXtmA499Xw6x15LVJSuVgsp43CXBKdnyQsoZy3ezVI314=
  ## use file glob for wildcards
  file_glob: true
  file: 
    - "build/Galactic Science_*_Client.zip"
    - "build/Galactic Science_*_Server.zip"
  ## only deploy tags/versions
  on:
    tags: true