language: java
# Only build tags
if: tag IS present
install:
- true
script:
- gradle buildAll
deploy:
  provider: releases
  api_key:
    secure: p5LpQNkOka2zGegvABl/yuZDuZpp+guVQ63122WK2B16ySJdxWSRjnDQi2aHIVm09dzic6aVAjGkdK2GAL+/8gq4QxkhEvVuUSx+Gl+LuTRjwK403AMDt5WyJ4+DNXWZLM7TXdnoakcsTg9ikqZXDc9ircJO5TanqP5GX4HTSR1w51xRnmjXlYxLiFvnwR01ykcyrWaLm3Y3H1k4h1DlEnkfSVnT7QjEhBl7z7HpsHeGy8JPqZENM+r7tpPmSyhf5vuNLsvZz2R+TOo2wTiLQH2FC4MvtRjbREzIUsT9vcpnzjI9X8ha07xPI9utvf98Z2z7rQpKFDgvD8taaxdn6uDTWSltWp6/YrB8AFMqZa+Sjt5n41RAP2m6/xLqM5SuyiZzmlTl7Dp86Xb8Kz3fGTnKGpssbtIKK1lZRbDvY3fOc3k6+nFUVP+enckmBOPMR4E95DZmFW4+ufJmxs7LSOJ6K8nqsO9EjpFIbIAPN+36N2fGSqTbpJUOCvo4sZVFQa1VBv8Ag8jWmY2WLjng9sPPo/a52yRGyH7TVsZJ3FE/R23SG9oAAv+wV74NBFmiaXvih8DIP/vXdnNaW3omaAS1cGvXnofJJn6CtM90KQQMmh3I9yox6SCyPg8akZ9v8DIkNde/vGdCx0Tfe4mIIf3FUf51kIID64KxEji5DgI=
  file_glob: true
  file:
  - build/Galactic Science_*_Client.zip
  - build/Galactic Science_*_CurseProfile.zip
  - build/Galactic Science_*_Server.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: mZbXFMRQLQ0Ej3FNFzdlX99+Ma68wLhCsaE2Gbz8JLeBxUzuHSCUZgA5dnqSi2/akDBQO6s1ekUxzWuM6/Plh4bUX/xeIL+SqQ3j0I2Txj5GIGQJN9Is+pe1dL858pVM0o+MzjB6d170/OkO4IjahNq935M3v20/YbXWytOmY2vvFp0GYwshrWrb/dnhUhMLdW8Ya80a2wAKFx/XvhQSGTtv/a+FKSwcNPdIqXh1RGjJKx5LsNQQF4f/+tTU6pIFyeJcRtLVN2t+4rHorVHCX76g7yI6HxQz87+mLhgtLmRvaol4rMPfGWj4LEFqB2ym7WIA9YBkN3x1JGjKJBmOofztd57GBFST2hiqp9+C6uX0TL1KN3U7mAmKkPtaptzGjBlHp6j6yzC17YfP+EowdxFsrJLoqP5KBJPkUrEQGBBeTPbi9aSaKM7tamX4nK5L0beq6uMjqUCbbthPNlFh8DBiDKpBjpukOPPgUFh8/zvhnyc2jk4xqrhfGQkMlMtCv402Dtiwdlhi7yYaaYqxhMHPvLI8CTM4vchHWcm460tksM1H5vyDza0YqlNnJ2rMGjyz+Z8OMzy18WmIeuNi9A+xPSkMLj6GtEPG3kTR4ftcNaspRruLIbt5Zkf8Q0z6MZTg3tN1lS/ORhNtS0TrU6la/RgmmOl8RwX1SXkyPBk=
