language: java
# Only build tags
if: tag IS present
install:
- true
script:
- gradle buildAll
deploy:
  provider: releases
  api_key:
    secure: pesWhNu0AkU9927OvQ3zni4QUMCMe0dEgHtDan9TYTLtG0dAVf/iiUvbOYZYhm49zYVVuPL7xz1A2VseJ6nrVMwUnLk5rSDhEp8P38x2maZ87TqOE+s4DmehvgO7oa0hPupmwUkm48Gap5ZoqIAmLZ7injHY1HjzfbsUk14PldR2lm5UG4HPdciWzf6tR/4mc5p0rMltWgojwgeOR1YR9eW/y4cD325bgBNIaAi0TuY3KAA1f/XaF7Nj+CnGQQdK710tkUzZ51Uht/VWl6RsUk4VIP2tcssYZ1Fgx6u1MboMq5pealE2knwN7LqRREEnbMMlca8ONbr1OYUK7F5xeef2fuhEeqNhziz7QlfVUQEK9qcQG/iaIlxf5/C+s9Mgpq5ZZzNnRu2OelKt/5vBl/BTEPFycOfWeWY1lOUz62waF5LE0rDWi1ZICK3eKV0IN6SwsOJoO8R4Epw5L/8tSsGVy0pigw48VOsWkjQs54ZTB2mTzy+vjsuLCVL6ewiXSynvMA9WklqRs19/N8cFdCUQCwygTM6jnJQxgZzoRSsM3rzPzHySOD7f2Rp5uTioYG0baXaZS2+/vPqJoJUX0iELsRkoX83e8vwBkHWBs0HqZAb8mxb50vhEdz1OQmSEZVyxBy2CLUuxxJXFaX8YC/6BEWzlCdQLO1LHxqNakY4=
  file_glob: true
  file:
  - build/Galactic Science_*_Client.zip
  - build/Galactic Science_*_Server.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: mZbXFMRQLQ0Ej3FNFzdlX99+Ma68wLhCsaE2Gbz8JLeBxUzuHSCUZgA5dnqSi2/akDBQO6s1ekUxzWuM6/Plh4bUX/xeIL+SqQ3j0I2Txj5GIGQJN9Is+pe1dL858pVM0o+MzjB6d170/OkO4IjahNq935M3v20/YbXWytOmY2vvFp0GYwshrWrb/dnhUhMLdW8Ya80a2wAKFx/XvhQSGTtv/a+FKSwcNPdIqXh1RGjJKx5LsNQQF4f/+tTU6pIFyeJcRtLVN2t+4rHorVHCX76g7yI6HxQz87+mLhgtLmRvaol4rMPfGWj4LEFqB2ym7WIA9YBkN3x1JGjKJBmOofztd57GBFST2hiqp9+C6uX0TL1KN3U7mAmKkPtaptzGjBlHp6j6yzC17YfP+EowdxFsrJLoqP5KBJPkUrEQGBBeTPbi9aSaKM7tamX4nK5L0beq6uMjqUCbbthPNlFh8DBiDKpBjpukOPPgUFh8/zvhnyc2jk4xqrhfGQkMlMtCv402Dtiwdlhi7yYaaYqxhMHPvLI8CTM4vchHWcm460tksM1H5vyDza0YqlNnJ2rMGjyz+Z8OMzy18WmIeuNi9A+xPSkMLj6GtEPG3kTR4ftcNaspRruLIbt5Zkf8Q0z6MZTg3tN1lS/ORhNtS0TrU6la/RgmmOl8RwX1SXkyPBk=
